name: geprek_masdion
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0-247.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  lottie: 1.3.0
  path: 1.8.2
  firebase_core: 1.19.2
  firebase_auth: 3.4.2
  image_picker: 0.8.5+3
  cloud_firestore: 3.3.0
  firebase_storage: 10.3.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/lottie/
    - assets/icons/
  uses-material-design: true

